name: test_driftmlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.10,<=1.20
  - jupyter
  - ipywidgets
  - cartopy
  - appmode
  - pip:
    - git+https://github.com/MikeOMa/DriftMLP.git
