name: test_driftmlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy>=1.10,<=1.20
  - jupyter<=6.4.0
  - ipywidgets
  - cartopy
  - pip==21.1.1
  - appmode
  - pip:
    - git+https://github.com/MikeOMa/DriftMLP.git
